import { Button, Heading } from '@acme/ui'
import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ACME - Events Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>Events Admin</Heading>
        <br />
        <input className={styles.input} type="text" placeholder="Event name" />
        <br />
        <input className={styles.input} type="text" placeholder="Event date" />
        <br />
        <Button>Add</Button>
        <br />
        <br />
        <p>Copyright 2022 ACME</p>
      </main>
    </div>
  )
}

export default Home
